# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/constr/PYNQ-Z2 v1.0.xdc

# Block Designs: bd/design_2/design_2.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2 || ORIG_REF_NAME==design_2} -quiet] -quiet

# IP: bd/design_2/ip/design_2_processing_system7_0_0/design_2_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_processing_system7_0_0 || ORIG_REF_NAME==design_2_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_axi_iic_0_0/design_2_axi_iic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_axi_iic_0_0 || ORIG_REF_NAME==design_2_axi_iic_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_ps7_0_axi_periph_0/design_2_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_ps7_0_axi_periph_0 || ORIG_REF_NAME==design_2_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_rst_ps7_0_50M_0/design_2_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_rst_ps7_0_50M_0 || ORIG_REF_NAME==design_2_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_I2S_Receiver_0_0/design_2_I2S_Receiver_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_I2S_Receiver_0_0 || ORIG_REF_NAME==design_2_I2S_Receiver_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_I2S_Transmitter_0_0/design_2_I2S_Transmitter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_I2S_Transmitter_0_0 || ORIG_REF_NAME==design_2_I2S_Transmitter_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_Buffers_0_0/design_2_Buffers_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_Buffers_0_0 || ORIG_REF_NAME==design_2_Buffers_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_xbar_0/design_2_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_xbar_0 || ORIG_REF_NAME==design_2_xbar_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_axi_apb_bridge_0_0/design_2_axi_apb_bridge_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_axi_apb_bridge_0_0 || ORIG_REF_NAME==design_2_axi_apb_bridge_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_Button_ctrl_0_0/design_2_Button_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_Button_ctrl_0_0 || ORIG_REF_NAME==design_2_Button_ctrl_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_EQ_0_0/design_2_EQ_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_EQ_0_0 || ORIG_REF_NAME==design_2_EQ_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_EQ_1_0/design_2_EQ_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_EQ_1_0 || ORIG_REF_NAME==design_2_EQ_1_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_EQ_2_0/design_2_EQ_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_EQ_2_0 || ORIG_REF_NAME==design_2_EQ_2_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_EQ_3_0/design_2_EQ_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_EQ_3_0 || ORIG_REF_NAME==design_2_EQ_3_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_AXI_comb_0_0/design_2_AXI_comb_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_AXI_comb_0_0 || ORIG_REF_NAME==design_2_AXI_comb_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_AXI_comb_1_0/design_2_AXI_comb_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_AXI_comb_1_0 || ORIG_REF_NAME==design_2_AXI_comb_1_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_AXI_lowpass_0_0/design_2_AXI_lowpass_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_AXI_lowpass_0_0 || ORIG_REF_NAME==design_2_AXI_lowpass_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_AXI_comb_2_0/design_2_AXI_comb_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_AXI_comb_2_0 || ORIG_REF_NAME==design_2_AXI_comb_2_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_AXI_comb_3_0/design_2_AXI_comb_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_AXI_comb_3_0 || ORIG_REF_NAME==design_2_AXI_comb_3_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_AXI_lowpass_1_0/design_2_AXI_lowpass_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_AXI_lowpass_1_0 || ORIG_REF_NAME==design_2_AXI_lowpass_1_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_AXI_lowpass_2_0/design_2_AXI_lowpass_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_AXI_lowpass_2_0 || ORIG_REF_NAME==design_2_AXI_lowpass_2_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_AXI_early_reflection_0_0/design_2_AXI_early_reflection_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_AXI_early_reflection_0_0 || ORIG_REF_NAME==design_2_AXI_early_reflection_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_xlconstant_0_0/design_2_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_xlconstant_0_0 || ORIG_REF_NAME==design_2_xlconstant_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_AXI_lowpass_3_0/design_2_AXI_lowpass_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_AXI_lowpass_3_0 || ORIG_REF_NAME==design_2_AXI_lowpass_3_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_AXI_Allpass_0_0/design_2_AXI_Allpass_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_AXI_Allpass_0_0 || ORIG_REF_NAME==design_2_AXI_Allpass_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_AXI_ADD_4_0_0/design_2_AXI_ADD_4_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_AXI_ADD_4_0_0 || ORIG_REF_NAME==design_2_AXI_ADD_4_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_AXI_pitch_shift_0_3/design_2_AXI_pitch_shift_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_AXI_pitch_shift_0_3 || ORIG_REF_NAME==design_2_AXI_pitch_shift_0_3} -quiet] -quiet

# IP: bd/design_2/ip/design_2_axi_apb_bridge_1_0/design_2_axi_apb_bridge_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_axi_apb_bridge_1_0 || ORIG_REF_NAME==design_2_axi_apb_bridge_1_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_AXI_ANF_0_7/design_2_AXI_ANF_0_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_AXI_ANF_0_7 || ORIG_REF_NAME==design_2_AXI_ANF_0_7} -quiet] -quiet

# IP: bd/design_2/ip/design_2_clk_wiz_0_0/design_2_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_clk_wiz_0_0 || ORIG_REF_NAME==design_2_clk_wiz_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_AXI_ADD_3_0_9/design_2_AXI_ADD_3_0_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_AXI_ADD_3_0_9 || ORIG_REF_NAME==design_2_AXI_ADD_3_0_9} -quiet] -quiet

# IP: bd/design_2/ip/design_2_auto_pc_0/design_2_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_auto_pc_0 || ORIG_REF_NAME==design_2_auto_pc_0} -quiet] -quiet

# XDC: bd/design_2/design_2_ooc.xdc
